# Generated by Django 5.2.4 on 2025-08-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_id', models.CharField(max_length=20, unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('birth_date', models.DateField()),
                ('contact', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'PatientList',
            },
        ),
    ]
