# Generated by Django 5.2.4 on 2025-07-23 12:17
from django.db import migrations, models

class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('doc_type', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='documents/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
