# Generated by Django 5.2.4 on 2025-08-19 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_register_tables'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medical_certificate',
            options={'managed': False, 'verbose_name': '진료확인서', 'verbose_name_plural': '진료확인서 목록'},
        ),
        migrations.AlterModelOptions(
            name='medicalreceipt',
            options={'managed': False, 'verbose_name': '진료영수증', 'verbose_name_plural': '진료영수증 목록'},
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={'managed': False, 'verbose_name': '처방전', 'verbose_name_plural': '처방전 목록'},
        ),
    ]
